export const RESPONSE_META_DATA = 'RESPONSE_META_DATA';
export const RESPONSE_TYPE_META_DATA = 'RESPONSE_TYPE_META_DATA';
export const PATH_META_DATA = 'PATH_META_DATA';
export const PATH_PARAM_META_DATA = 'PATH_PARAM_META_DATA';
export const BODY_META_DATA = 'BODY_META_DATA';
export const HEADER_META_DATA = 'HEADER_META_DATA';
export const QUERY_META_DATA = 'QUERY_META_DATA';