export const HTTP_CLIENT_META_DATA = 'HTTP_CLIENT_META_DATA';
export const RESPONSE_META_DATA = 'RESPONSE_META_DATA';
export const RESPONSE_TYPE_META_DATA = 'RESPONSE_TYPE_META_DATA';
export const PATH_PARAM_META_DATA = 'PATH_PARAM_META_DATA';
