name: github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v3

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@serglenkov'

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run pack-and-publish
